//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blogs.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class blog_tb_article_extend 
    {
        public int articleID { get; set; }
        public Nullable<System.DateTime> lastOpenDatetime { get; set; }
        public string lastOpenIP { get; set; }
        public string lastOpenUserID { get; set; }
        public Nullable<int> articleClickTimes { get; set; }
        public int articleCommentTimes { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
    
    }
}
