//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blogs.Entity
{
    using System;
    using System.Collections.Generic;

    public partial class blog_tb_log 
    {
        public string logID { get; set; }
        public string logSystem { get; set; }
        public string logUrl { get; set; }
        public string logClass { get; set; }
        public string userID { get; set; }
        public string userName { get; set; }
        public string logIP { get; set; }
        public string logTitle { get; set; }
        public string logContent { get; set; }
        public string exSource { get; set; }
        public string exStackTrace { get; set; }
        public string logRemark { get; set; }
        public System.DateTime ADD_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string logLevel { get; set; }
    }
}
