//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Blogs.Entity 
{
    public partial class blog_tb_article_content 
    {
      
        public int articleID { get; set; }
        public int blogID { get; set; }
        public string articleContent { get; set; }
        public string articleContent2 { get; set; }
        public string articleSubContentText { get; set; }
        public string articleSubContentHtml { get; set; }
        public string articleSourceHtml { get; set; }
        public string articleSourceContent { get; set; }
        public string articleHideContent { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
    
    }
}
