//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blogs.Entity
{
    using System;
    using System.Collections.Generic;

    public partial class blog_tb_link 
    {
        public string linkID { get; set; }
        public int blogID { get; set; }
        public string linkName { get; set; }
        public string linkUrl { get; set; }
        public string linkPic { get; set; }
        public int linkOrder { get; set; }
        public bool linkIsDisabled { get; set; }
        public System.DateTime ADD_DATE { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }

    }
}
