//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blogs.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class blog_tb_VisitCount
    {
        public string ID { get; set; }
        public string SiteID { get; set; }
        public string Domain { get; set; }
        public int UV { get; set; }
        public int PV { get; set; }
        public int IP { get; set; }
        public int AddUV { get; set; }
        public int AddPV { get; set; }
        public int AddIP { get; set; }
        public System.DateTime CountDate { get; set; }
        public System.DateTime ADD_DATE { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
    }
}
